### ISSUE TITLE
1.0.7 release does not have the .saver file available

### ISSUE THREAD

**Issue by JaKXz** [leonspok/Irvue-Screensaver#10]
Hi, thank you for this project!

At time of writing, https://github.com/leonspok/Irvue-Screensaver/releases/latest does not have the link to the `.saver` file and only lets me download the source code.

I could build it from source, if there were instructions, but I think just having the artifact there would be easier :) thanks again!

**Comment by bsdahl** [comment]
Hi @JaKXz, I think it was initially present but then taken down for some reason. Either way, I was able to download the 1.0.7 saver when it was available. Give this one a try.

**Comment by leonspok** [comment]
Sorry, @bsdahl, I had to edit your comment to remove the link to v1.0.7. I used API keys from the main app in this build (that was a huge mistake), but then I found that this screensaver makes too many requests and because of this Irvue reaches API rate limit too fast.

For now you can build screensaver with your own API keys (register your app here: https://unsplash.com/oauth/applications). Or you can [email me](mailto:igor9774@gmail.com) your keys and I will build it for you. 

You can keep track on issue #12 and issue #13.

cc @JaKXz

**Comment by bsdahl** [comment]
@leonspok no problem! I completely understand.
